// Code generated by "stringer -type=Location"; DO NOT EDIT.

package slot

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[None-0]
	_ = x[Wield-1]
	_ = x[Hold-2]
	_ = x[Head-3]
	_ = x[Neck-4]
	_ = x[Body-5]
	_ = x[About_Body-6]
	_ = x[Legs-7]
	_ = x[Feet-8]
	_ = x[Arms-9]
	_ = x[Wrist-10]
	_ = x[Hands-11]
	_ = x[Fingers-12]
	_ = x[Waist-13]
}

const _Location_name = "NoneWieldHoldHeadNeckBodyAbout_BodyLegsFeetArmsWristHandsFingersWaist"

var _Location_index = [...]uint8{0, 4, 9, 13, 17, 21, 25, 35, 39, 43, 47, 52, 57, 64, 69}

func (i Location) String() string {
	if i < 0 || i >= Location(len(_Location_index)-1) {
		return "Location(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Location_name[_Location_index[i]:_Location_index[i+1]]
}
